services:
  detector:
    build: .
    container_name: lot_detector
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "find /tmp/healthy -mmin -1 || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
